language: node_js

node_js:
  - "stable"

before_install:


after_success:
- npm install -g firebase-tools

deploy:
  provider: firebase
  token:
    secure: $FIREBASE_TOKEN
  project: "robotics-club-cit"